apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio-edge
  namespace: portfolio
spec:
  entryPoints:
    - web
  routes:
    # Backend swagger/openapi (rutas reales de FastAPI)
    - match: PathPrefix(`/docs`) || PathPrefix(`/openapi.json`)
      kind: Rule
      services:
        - name: backend
          port: 8000

    # Backend API real
    - match: PathPrefix(`/api/v1`)
      kind: Rule
      services:
        - name: backend
          port: 8000

    # Frontend
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          port: 80
